In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [7]:
b = np.array([[1.2, 2.4, 5.4], [3.0, 6.9, 9.2]])

In [8]:
print(b)

[[1.2 2.4 5.4]
 [3.  6.9 9.2]]


In [12]:
a.shape

(3,)

In [13]:
b.shape

(2, 3)

In [21]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [22]:
c.shape

(2, 7)

In [23]:
c[1,5]

13

In [24]:
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
c[1,-2]

13

In [28]:
c[0]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
c[:,2]

array([ 3, 10])

In [32]:
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
d = np.array([1,1,1,1,1])
print(d)

[1 1 1 1 1]


In [46]:
print(np.ones(5, dtype='int32'))

[1 1 1 1 1]


In [44]:
print(np.full((2), 1))

[1 1]


In [59]:
arr_ones = np.ones((5,5))

In [55]:
r1 = np.repeat(arr, 3, axis=0)

In [60]:
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [63]:
arr_ones[1:-1, 1:-1] = z

In [64]:
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
a = np.array([1,2,3])
b = a.copy()

In [72]:
print(a)

[1 2 3]


In [73]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])


In [78]:
after = a1.reshape(1,3)
print(after)

[[1 2 3]]


In [80]:
np.vstack([a1,a2,a1,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])